<?php
/**
 * @file
 * 
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function siteapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.siteapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module also provides a URL that responds with a JSON representation of a given node with the content type "page" only if the previously submitted API Key and a node id (nid) of an appropriate node are present, otherwise it will respond with "access denied"') . '</p>';
       return $output;
  }
}

